services:
  db:
    image: postgres:16-alpine
    container_name: parking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_password
      POSTGRES_DB: parking_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  postgres_data:
