default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: parking_development
  username: parking_user
  password: parking_password
  host: localhost
  port: 5432

test:
  <<: *default
  database: parking_test
  username: parking_user
  password: parking_password
  host: localhost
  port: 5432